const gameData = [
  {
    id: 1,
    isHover: false,
    isGreen: false,
    isStar: true,
    point: 10,
    pointArr: [0],
  },
  {
    id: 2,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 3,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 4,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 5,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 6,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 7,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 8,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 9,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 10,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 11,
    isHover: false,
    isGreen: false,
    isStar: false,
    point: 5,
    pointArr: [1, 2, 3, 4, 5],
  },
  {
    id: 12,
    isHover: false,
    isGreen: false,
    isStar: true,
    point: 10,
    pointArr: [0],
  },
];

export default gameData;
